### ISSUE TITLE
Option to use reportValidity vs checkValidity in submit

### ISSUE THREAD

**Issue by ashaffer** [dominicbarnes/deku-forms#1]
I'm thinking of using this for my own forms, but i'd really like to be able to show my validation messages if the user presses submit but hasn't entered anything yet.  I think using reportValidity would allow this to work.

Btw, awesome idea to use the html5 validation stuff.  I had been struggling to find a good, abstract way to implement forms in deku and this is just very clearly the right way to do it.  Much cleaner than the stuff I was trying.

EDIT: Nvm, I think I am misunderstanding the use-case of reportValidity.

**Comment by dominicbarnes** [comment]
Thanks for taking the time to look at this component! If you have any other feedback, please don't hesitate to reach out again.
