### ISSUE TITLE
Not isomorphic

### ISSUE THREAD

**Issue by kvnneff** [dominicbarnes/deku-forms#4]
`component-value` has `component-type` as a dependency and uses as a require statement `require('type')`.  `component-value` has a `package.json` with a browser field setting the module name to `type` so that it will work with browserify, however in node it will throw an `Error: Cannot find module 'type'`.

**Comment by dominicbarnes** [comment]
Ah bummer, I was afraid something like this would happen. I'll see what I can do to resolve this soon.

**Comment by dominicbarnes** [comment]
This should be resolved now
